source "https://rubygems.org"

gem "rails", "~> 6.0.0"
gem "blazer"
gem "puma"
gem "tzinfo-data"

# data stores
gem "activerecord6-redshift-adapter"
gem "aws-sdk-athena"
gem "aws-sdk-glue"
gem "drill-sergeant"
gem "cassandra-driver"
gem "elasticsearch", "< 7.14"
gem "elasticsearch-xpack", "< 7.14"
gem "google-cloud-bigquery"
gem "hexspace"
# gem "ibm_db"
gem "ignite-client"
gem "mongo"
gem "mysql2"
gem "neo4j-core"
# gem "activerecord-oracle_enhanced-adapter"
# gem "ruby-oci8" # for oracle
gem "pg"
gem "presto-client"
gem "restforce"
# gem "odbc_adapter" # TODO add snowflake driver
gem "sqlite3"
# gem "tiny_tds"
# gem "activerecord-sqlserver-adapter"
